#!/bin/bash
echo "Monitoring directories:"

monitored_files=""
for f in "$@"
do
    if [ ! -d "$1" ] ; then
        break
    fi
    echo $1
    monitored_files="$monitored_files $f"
    shift
done

echo ""

echo "and running commands:"
for c in "$@"
do
    echo $c
done

echo ""

for cmd in "$@"
do
	$cmd
done

# while inotifywait -e close_write -e attrib $monitored_files
inotifywait -m -e close_write -e attrib -r $monitored_files | 
while read -r path action file
do
    if [[ "$file" =~ .*elm$ ]]; then # Does the file end with .xml?
        echo "$action: $path"
        for cmd in "$@"
        do
            $cmd
        done
    fi
done
