version: '3'
services:
    dating:
        build: ./
        image: dating
        command: bash -c "ghcid --command=\"stack --allow-different-user ghci\" --test=\"Main.main\"" 
        volumes:
          - ./:/app/user
        ports:
           - "1234:1234"

    elm:
        build: ./docker/elm
        image: elm
        volumes:
            - ./frontend/:/opt/app
        command: "bash -c \"shopt -s globstar; onchange ./src/ \\\"elm make src/Main.elm --output main.js --debug\\\"\""

    caddy:
      image: abiosoft/caddy
      ports:
        - "80:80"
      volumes:
        - "./frontend:/srv/elm-frontend"
        - "./docker/caddy/Caddyfile:/etc/Caddyfile"

    sass:
      image: larryprice/sass
      volumes:
        - ./frontend/style:/src

    redis:
      image: redis:4.0

    mongodb:
        image: 'bitnami/mongodb:latest'
        user: root
        ports:
            - "8020:27017"
        environment:
            - MONGODB_ROOT_PASSWORD=strangerdanger
            - MONGODB_USERNAME=datingdbuser
            - MONGODB_PASSWORD=datingdbpassword
            - MONGODB_DATABASE=datingdb
        volumes:
            - ./docker/mongodb/data:/bitnami
        logging:
            driver: "none"
