version: '3'
services:
    dating:
        build: .
        image: dating
        command: dating
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - dating
