version: '3'
services:
    postgres:
        image: postgres:9.6
        ports:
          - "5432:5432"
    redis:
      image: redis:4.0
      ports:
        - "6379:6379"
    dating:
        build: ./docker/dating
        image: dating
        command: bash -c "ghcid --command=\"stack --allow-different-user ghci\" --test=\"Main.main\"" 
        volumes:
          - ./:/app/user
        ports:
           - "1234:1234"
    nginx:
        build: ./docker/nginx
        image: nginx
        ports:
          - "8080:80"

    elm-reactor:
        build: ./docker/elm
        image: elm
        volumes:
            - ./frontend/:/opt/app
        ports:
            - "8000:8000"
        command: "reactor"
