version: '3'
services:
    postgres:
        image: postgres:9.6
        ports:
          - "5432:5432"
    redis:
      image: redis:4.0
      ports:
        - "6379:6379"
    dating:
        build: ./
        image: dating
        command: bash -c "ghcid --command=\"stack --allow-different-user ghci\" --test=\"Main.main\"" 
        volumes:
          - ./:/app/user
        ports:
           - "1234:1234"

    nginx:
        build: ./docker/nginx
        image: nginx
        ports:
          - "8002:80"
    

    caddy:
      image: abiosoft/caddy
      ports:
        - "80:80"
#        - "443:443"
      volumes:
        - "./frontend:/srv/elm-frontend"
        - "./docker/caddy/Caddyfile:/etc/Caddyfile"

    elm:
        build: ./docker/elm
        image: elm
        volumes:
            - ./frontend/:/opt/app
        ports:
            - "8001:8000"
        #command: "onchange .gitignore 'cat .gitignore'"
        command: "onchange src/ \"elm make src/Main.elm --output index.html\""
