name: dating
version: '0.1.0.0'
category: Web
author: Kasper Dissing Bargsteen
maintainer: kasper@bargsteen.com
copyright: Kasper Dissing Bargsteen
license: BSD3
github: bargsteen/dating
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - API
  - Database
  - Schema
  - SchemaEnums
  - FrontendTypes
  dependencies:
  - base >=4.7 && <5
  - wai
  - aeson
  - monad-logger
  - bson
  - mtl
  - persistent
  - persistent-template
  - persistent-mongoDB
  - servant
  - servant-client
  - servant-elm
  - servant-server
  - transformers
  - text
  - warp
  - hedis
  - bytestring
  - wai-cors
  - time
  - cookie
  - containers
  - http-client
  - servant-foreign
  - random
  - network
  - template-haskell
  - generic-lens
  - lens
  - mongoDB
  - QuickCheck
  - quickcheck-text
  - quickcheck-instances
  - cryptonite
  - JuicyPixels
  - base64-bytestring
  - strict
  - hmatrix
  - directory
executables:
  dating:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - base
    - dating
tests:
  dating-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - base
    - hspec
    - QuickCheck
    - http-client
    - http-client-tls
    - monad-logger
    - mtl
    - servant-client
    - persistent-postgresql
    - dating
